tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "bat"
brew "direnv"
brew "fd"
brew "fzf"
brew "git-delta"
brew "lsd"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "starship"
brew "zoxide"
cask "amethyst"
cask "font-fira-mono-nerd-font"
cask "kitty"
