brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "zoxide"

tap "nikitabobko/tap"

cask "1password"
cask "1password-cli"
cask "amethyst"
cask "font-jetbrains-mono"
cask "font-symbols-only-nerd-font"
cask "ghostty@tip"
