tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "bat"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "zoxide"

cask "amethyst"
cask "font-jetbrains-mono"
cask "font-symbols-only-nerd-font"
