# Configure XDG before most things
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# Create basic configuration variables
export DOTS=$HOME/.dotfiles
CUSTOM=$DOTS/custom

# Set configuration variables for applications to use XDG
source $DOTS/zsh/config_dirs.zsh

# Load custom shell scripts
if [[ -d "$CUSTOM" ]]; then
    for custom_file ($CUSTOM/*.zsh) source $custom_file
fi

